# -*- coding: utf-8 -*-
"""Punto5_arquimedes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUHOoerVavNVJ91BvcnrefvrtSRlUXWP
"""

import numpy as np
import matplotlib.pyplot as plt


def arq(a,b):
  theta=np.linspace(0,2*3.1416)
  r=a+b*theta
  x=r*np.cos(theta)
  y =r*np.sin(theta)
  return plt.plot(x,y)
  
arq(0,1)

