# -*- coding: utf-8 -*-
"""Punto3_variaciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUHOoerVavNVJ91BvcnrefvrtSRlUXWP
"""

import math
def variaciones(n,r):
  denominador= math.factorial(n)
  numerador= math.factorial((n-r))
  resultado= int(denominador/numerador)
  print("Las variaciones sin repetición totales son: "+str(resultado))

y= int(input("Ingrese el número n a calcular: "))
z= int(input("Ingrese el segundo número (r): "))
variaciones(y,z)