# -*- coding: utf-8 -*-
"""Punto5_primos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUHOoerVavNVJ91BvcnrefvrtSRlUXWP
"""

import matplotlib.pyplot as plt
import numpy as np

cantidad = 1000
cont = 0
lista=[]
for i in range(2, cantidad*10):
    primos = True
    for j in range(2,i):
        if i == j:
           break
        elif i%j == 0:
           primos = False
        else:
           continue
    if primos == True:
        lista.append(i)
        cont += 1
        if cont==10:
          print("Los primeros 10 números primos son:")
          print(lista)
        elif cont==cantidad:
          break
        else:
          continue
x=np.linspace(1,cantidad,cantidad)
plt.plot(x,lista, color="r",linewidth=3)

