# -*- coding: utf-8 -*-
"""Punto3_combinaciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUHOoerVavNVJ91BvcnrefvrtSRlUXWP
"""

import math
def combinaciones(n,m,x):
  if n>m:
    if x=="F":
      denominador=math.factorial(n)
      numerador = (math.factorial(m))*(math.factorial(n-m))
      resultado = int(denominador/numerador)
      return resultado
    else:
      denominador=math.factorial(n-1)
      numerador = (math.factorial(m-1))*(math.factorial(n-m))
      resultado = int(denominador/numerador)
      return resultado
  else:
    return 0

c= int(input("Ingrese el número n a calcular: "))
d= int(input("Ingrese el segundo número (m): "))
e= input("Conteste con T o F si se sabe quién será el arquero: ").upper()
combinaciones(c,d,e)