# -*- coding: utf-8 -*-
"""Punto5_arquimedes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dr8IsjrFulybn7Na1_MOs4_Sj66mDWpO
"""

import numpy as np
import matplotlib.pyplot as plt

#En el doc decía de 0 a 2pi, pero la imagen del mismo es en realidad con el ángulo hasta 6pi.

def arq(a,b):
  theta=np.linspace(0,6*np.pi,200)
  r=a+b*theta
  x=r*np.cos(theta)
  y =r*np.sin(theta)
  return plt.plot(x,y)
  
arq(0,1)

