# -*- coding: utf-8 -*-
"""Punto3_factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUHOoerVavNVJ91BvcnrefvrtSRlUXWP
"""

def factorial(b):
  fact=0
  if b==0 or b==1:
    fact=1
  if b<0:
    print("Error")
  else:
    fact =1
    for i in range(1,b+1):
      fact=fact*i
  return fact

def fact_varios(x):
  lista=[]
  for i in range(x+1):
    fact=factorial(i)
    lista.append(fact)
  print(lista)

fact_varios(20)