# -*- coding: utf-8 -*-
"""Punto5_fibonacci_aureos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUHOoerVavNVJ91BvcnrefvrtSRlUXWP
"""

import numpy as np
import matplotlib.pyplot as plt

def fibo(n):
  if n<2:
    return n
  else:
    return (fibo(n-1)+fibo(n-2))

def listar(): 
  lista=[]
  for i in range(21):
    numero=fibo(i)
    lista.append(numero)
  print(lista)
  x=np.linspace(0,20,21)
  y= np.array(lista)
  plt.plot(x,y,color="black",linewidth=2)
  plt.legend(['Serie Fibonacci'])
  plt.show()

listar()

import math
import numpy as np
import matplotlib.pyplot as plt

def aureo():
  real=(1+math.sqrt(5))/2
  lista_aureos=[]
  for i in range(20):
    lista_aureos.append(real)
  lista_estimados=[]
  for i in range(2,21):
    lista_estimados.append((fibo(i))/(fibo(i-1)))
  
  x=np.linspace(0,19,19)
  x2=np.linspace(0,20,20)
  plt.plot(x,lista_estimados)
  plt.plot(x2,lista_aureos,"r--",color="r")
  plt.xlim(-0.6,18)
  plt.legend(['Estimación usando la serie', 'Número aureo'])
  
    
aureo()