# -*- coding: utf-8 -*-
"""Punto1.3_derivada1kernel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BEpNONUu0fuVeRFKuqoOBi6FcCaP4Rzf
"""

#Punto 1.3
import numpy as np
import matplotlib.pyplot as plt


def derivar(h):
  f = lambda x: 1/np.sqrt(1+np.exp(-x**2))
  X=np.arange(-10,10,h)
  Y=np.zeros(len(X))
  M=np.array([-1,0,1])
  for i in range(1,len(X)-1):
    F=np.array([f(X[i-1]),f(X[i]),f(X[i+1])])
    Y[i]=np.dot(F/(2*h),M)
  return Y
  
h=0.05
y=derivar(h)
x=np.arange(-10,10,h)
fig = plt.figure(figsize=(7,3))
ax1 = fig.add_subplot(2,1,1)
ax1.scatter(x,y)
ax1.set_title("Primera derivada usando kernel")
plt.subplots_adjust(left=0.125,
                    bottom=0.0001, 
                    right=0.9, 
                    top=0.99, 
                    wspace=0.2, 
                    hspace=0.35)