# -*- coding: utf-8 -*-
"""Punto4b_derivada2kernel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JafX_zHzK-FbU44hWQJeMkD4ltEkpVlN
"""

#ahora hacer la segunda derivada con convolución
import numpy as np
import matplotlib.pyplot as plt

def segunda(h):
  f = lambda x: 1/np.sqrt(1+np.exp(-x**2))
  X=np.arange(-10,10,h)
  Y=np.zeros(len(X))
  M=np.array([1,0,-2,0,1])
  for i in range(2,len(X)-2):
    F=np.array([f(X[i-2]),f(X[i-1]),f(X[i]),f(X[i+1]),f(X[i+2])])
    Y[i]=np.dot(F/(4*(h**2)),M)
  return Y

h=0.05
y=segunda(h)
x=np.arange(-10,10,h)
fig = plt.figure(figsize=(7,3))
ax1 = fig.add_subplot(2,1,1)
ax1.scatter(x,y)