# -*- coding: utf-8 -*-
"""Punto1.2_derivadac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xw-ReKLHEAtzhNRGgIgG1qEja_ANSLxe
"""

#PUNTO 1.2. A Y B
#%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt

#Función para sacar derivada central
def DerivateC(x,f,h):
  respuesta= (f(x+h)-f(x-h))/(2*h)
  return respuesta

x= np.linspace(-10,10,2000)
h=0.05

#Función original 
f = lambda x: 1/np.sqrt(1+np.exp(-x**2))
derivada=DerivateC(x,f,h)

#Derivada real de la función para comparar el error
r = lambda x: (np.exp(-x**2)*x)/(np.exp(-x**2)+1)**(3/2)
real= r(x)

#grafica punto 1.2.B
#Primero se grafica la derivada central vs la derivada real en el mismo plot
fig = plt.figure(figsize=(7,3))
ax1 = fig.add_subplot(2,1,1)
ax1.scatter(x,derivada)
ax1.set_title("Primera derivada")
ax1.scatter(x,real)

#Abajo se grafica el error en cada punto de ambas derivadas
ax2 = fig.add_subplot(2,1,2)
ax2.scatter(x,np.abs(real-derivada))
ax2.set_title("Estimación del error")
plt.subplots_adjust(left=0.125,
                    bottom=0.0001, 
                    right=0.9, 
                    top=0.99, 
                    wspace=0.2, 
                    hspace=0.35)