# -*- coding: utf-8 -*-
"""parcial1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1js6A0ZagHYboLpJnrJQMiZ8Twsz-UPFc
"""

import numpy as np
import matplotlib.pyplot as plt

def DerivativeReg(x,f,h):
    return (-3*f(x)+4*f(x+h)-f(x+2*h))/2*h

def DerivativeC(x,f,h):
    return (f(x+h)-f(x-h))/(2*h)

h=0.01
a=0.1
b=1.1
x = np.arange(a,b,h)
f = lambda x: np.sqrt(np.tan(x))
y = f(x)

#Derivada real
sec=1/np.cos(x)
real = lambda x: (sec)**2/2*np.sqrt(np.tan(x))
r=real(x)

DerivadaR = DerivativeReg(x,f,h)
DerivadaC = DerivativeC(x,f,h)

fig = plt.figure(figsize=(7,3))
ax = fig.add_subplot(2,2,1)
ax1 = fig.add_subplot(2,2,2)
ax2 = fig.add_subplot(2,2,3)


ax.scatter(x,y)
ax1.scatter(x,DerivadaR, color="blue")
ax1.scatter(x,DerivadaC, color="green")

ax1.scatter(x,r,color="red")
ax2.scatter(x,np.abs(r-DerivadaR))
ax2.scatter(x,np.abs(r-DerivadaC))

