# -*- coding: utf-8 -*-
"""Punto8-Probabilidad

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OLf9KjNTm4ImvnlXwSzU6E_Wiiym4piM
"""

import numpy as np
import matplotlib.pyplot as plt
import random

total=0
N=1e5

for i in range (int(N)):
  m1=np.random.choice([-1,1])
  m2=np.random.choice([-1,1])
  m3=np.random.choice([-1,1])
  m4=np.random.choice([-1,1])
  suma=m1+m2+m3+m4
  if suma == 0: 
    total+=1
prob=total/N
print ("La probabilidad de obtener dos caras y dos sellos es: " +str(prob)+ " cuando se lanzan simultanemanete 4 monedas")







