# -*- coding: utf-8 -*-
"""Punto4_Probabilidad

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wfm1lnSiSFZm_x1GFdoiK28Qm9UAncwT
"""

import numpy as np
import matplotlib.pyplot as plt
import random

lista=[]
n=range(0,81)
for i in n: 
  #la formula general del calculo para que NO coindida el cumpleaños de n personas es: 
  # p = 365!/(356^n(365-n)!)
  formula=(np.math.factorial(365))/((365**i)*(np.math.factorial(365-i)))
  lista.append(formula)
fig = plt.figure(figsize=(5,5))
ax = fig.add_subplot(1,1,1)
ax.set_title('La Paradoja del Cumpleaños')
ax.set_xlabel('Numero de Personas')
ax.set_ylabel("Probabilidad*100 (para NO coincidir)")
ax.plot(n,lista,lw=3)