# -*- coding: utf-8 -*-
"""Punto3_Probabilidad

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PSBvf35r6HTAsKOMYoR8TzWCFf-jepV
"""

import numpy as np
import matplotlib.pyplot as plt
import random

#a) prob para uno de los dos servicios 
pambos_ab=0.5
pb=0.6
pa=0.8
ab=pa+pb-pambos_ab
r=round(ab,1)
print("La probabilidad es: " +str(r)+ " para que este suscripto a uno de los dos servicios")

#prob para uno de los dos servicios y no ambos
ba=ab-pambos_ab
r2=round(ba,1)
print("La probabilidad es: " +str(r2)+ " para que este suscripto al diario o al cable, pero no a ambos servicios")