# -*- coding: utf-8 -*-
"""Punto9_probabilidad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TYJL6y_XrFmuMaEhfPjm8lBIW1DJoK2G
"""

import numpy as np
import matplotlib.pyplot as plt
import random

p=np.linspace(0.1,0.9,100000)
p2=np.linspace(0.1,0.5,100000)
rta=np.zeros(np.shape(p))
for i in range(len(p)): 
  rta[i]=6*(p[i])**2*(1-p[i])**2 
max=np.max(rta)
n = np.argmax(rta)
print("En la posicion " +str(p[n])+ ";  ")
print("El valor maximo es : " +str(max)+ " para que las monedas esten truncadas")
min=np.min(rta)
n2 = np.argmin(rta)
print("En la posicion " +str(p[n2])+ ";  ")
print("El valor minimo es : " +str(min)+ " para que las monedas esten truncadas")

# grafica 
fig = plt.figure(figsize=(5,5))
ax = fig.add_subplot(1,1,1)
ax.set_title('Probabilidad del evento A')
ax.plot(p,rta,lw=3)